version: '3'
services:
  springboot-app:
    ports:
      - 8081:8080
    build:
      context: .
      args:
        JAR_FILE: /boot-cassandra.jar
    restart: always

  cassandradb:
    image: cassandra
    container_name: cassandradb
    ports:
      - "9042:9042"
      - "7000:7000"
